"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

/**
 * Looking again while the registry is still assembling.
 *
 * A package is generated by a worker after the request returns, so a
 * server-rendered list is a snapshot of a thing still moving. Without this the
 * screen says "being assembled" until somebody thinks to reload, which reads as
 * a stuck page rather than as work in progress.
 *
 * `router.refresh()` rather than a fetch: the list is server-rendered from the
 * registry, and re-rendering it on the server is what keeps one read path.
 * Fetching the same rows into client state would be a second, unvalidated copy
 * of the boundary this repo puts a Zod schema on.
 *
 * Deliberately bounded. A package still going after this has hit something the
 * registry has to work out — its lease expiring and another worker taking it, or
 * a failure landing on the row — and a tab left open for a day should not poll a
 * tenant API for a day. When the bound is spent the screen says so and offers
 * the one thing that helps.
 */

/** Slower than a spinner deserves, because a package takes as long as it takes. */
const EVERY_MS = 5_000;

/** Roughly two minutes. Past this, something is being worked out server-side. */
const ATTEMPTS = 24;

export function EvidencePackWatch({
  watching,
}: {
  watching: readonly string[];
}) {
  const router = useRouter();
  // What the budget was spent on, not merely that it was. A second package
  // requested after the first timed out is different work and gets its own
  // budget — recording *which* run gave up is what makes that fall out, and it
  // keeps the reset out of the effect body, where setting state would mean a
  // cascading render on every change of what is in flight.
  const [gaveUpOn, setGaveUpOn] = useState<string | null>(null);
  const run = watching.join(" ");

  // The budget belongs to the run, not to this effect. Held in the closure it
  // refilled on every re-render that re-ran the effect — and `router` is a
  // dependency, so anything returning a fresh one turned a bounded watch into
  // an unbounded one. Which is the whole failure the bound exists to prevent.
  const budget = useRef({ run: "", left: ATTEMPTS });

  useEffect(() => {
    if (run === "") return;
    if (budget.current.run !== run) budget.current = { run, left: ATTEMPTS };

    const timer = setInterval(() => {
      if (budget.current.left <= 0) {
        clearInterval(timer);
        setGaveUpOn(run);
        return;
      }
      budget.current.left -= 1;
      router.refresh();
    }, EVERY_MS);

    return () => {
      clearInterval(timer);
    };
  }, [run, router]);

  if (run === "") return null;

  return (
    // Polite rather than assertive: this is progress, not an alert, and a
    // screen reader interrupted every five seconds by "still assembling" would
    // be worse served than by not being told at all.
    <p aria-live="polite" className="text-[11px] leading-4 text-mist">
      {gaveUpOn === run
        ? "Still assembling. This page has stopped checking — reload it to look again."
        : "Assembling. This page is checking for you and will update on its own."}
    </p>
  );
}
