"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

/**
 * Looking again while the registry is still assembling.
 *
 * A package is generated by a worker after the request returns, so a
 * server-rendered list is a snapshot of a thing still moving. Without this the
 * screen says "being assembled" until somebody thinks to reload, which reads as
 * a stuck page rather than as work in progress.
 *
 * `router.refresh()` rather than a fetch: the list is server-rendered from the
 * registry, and re-rendering it on the server is what keeps one read path.
 * Fetching the same rows into client state would be a second, unvalidated copy
 * of the boundary this repo puts a Zod schema on.
 *
 * Deliberately bounded, per package. A package still going after this has hit
 * something the registry has to work out — its lease expiring and another
 * worker taking it, or a failure landing on the row — and a tab left open for a
 * day should not poll a tenant API for a day. When every package being watched
 * has spent its bound the screen says so and offers the one thing that helps.
 */

/** Slower than a spinner deserves, because a package takes as long as it takes. */
const EVERY_MS = 5_000;

/** Roughly two minutes. Past this, something is being worked out server-side. */
const ATTEMPTS = 24;

const EMPTY: ReadonlySet<string> = new Set();

export function EvidencePackWatch({
  watching,
}: {
  watching: readonly string[];
}) {
  const router = useRouter();
  // Which packages this page gave up on, not merely that it gave up. A
  // package asked for afterwards is different work, so the screen goes back to
  // watching without anything having to reset a flag.
  const [gaveUp, setGaveUp] = useState<ReadonlySet<string>>(EMPTY);
  const run = watching.join(" ");
  const ids = run === "" ? [] : run.split(" ");
  const stopped = ids.length > 0 && ids.every((id) => gaveUp.has(id));

  // One budget per package, not one shared by whichever set is in flight. The
  // budget belongs outside this effect because `router` is a dependency, so
  // anything returning a fresh one would refill a budget held in the closure.
  // Keying it on the set had the same effect by another route: a package
  // finishing changes the set, which refilled the budget of every package
  // still in flight — so a package stuck in `generating`, which is exactly
  // what the bound exists for, polled for as long as the tab stayed open.
  const budget = useRef(new Map<string, number>());

  useEffect(() => {
    if (run === "") return;
    const left = budget.current;
    const watched = run.split(" ");
    // A package that has landed stops consuming its budget; one still in
    // flight keeps what it has already spent, and a new one arrives with a
    // budget of its own.
    for (const id of [...left.keys()])
      if (!watched.includes(id)) left.delete(id);
    for (const id of watched) if (!left.has(id)) left.set(id, ATTEMPTS);

    const timer = setInterval(() => {
      let polled = false;
      for (const id of watched) {
        const remaining = left.get(id) ?? 0;
        if (remaining > 0) {
          left.set(id, remaining - 1);
          polled = true;
        }
      }
      if (!polled) {
        clearInterval(timer);
        // The previous set is kept when it already says this, so React bails
        // out of the update. A fresh Set here would re-render, and under a
        // `router` that is a new object per render the effect would re-arm
        // this interval and give up again every five seconds for as long as
        // the tab stayed open.
        setGaveUp((previous) =>
          previous.size === watched.length &&
          watched.every((id) => previous.has(id))
            ? previous
            : new Set(watched),
        );
        return;
      }
      router.refresh();
    }, EVERY_MS);

    return () => {
      clearInterval(timer);
    };
  }, [run, router]);

  if (run === "") return null;

  return (
    // Polite rather than assertive: this is progress, not an alert, and a
    // screen reader interrupted every five seconds by "still assembling" would
    // be worse served than by not being told at all.
    <p aria-live="polite" className="text-[11px] leading-4 text-mist">
      {stopped
        ? "Still assembling. This page has stopped checking — reload it to look again."
        : "Assembling. This page is checking for you and will update on its own."}
    </p>
  );
}
