/**
 * The site's canonical external origin, shared by `metadataBase` in the root
 * layout and by `robots.ts` and `sitemap.ts`, both of which need absolute URLs.
 *
 * Not read from the environment: `AUTH_URL` is per-deployment and names the
 * preview host on a preview build, and a sitemap naming that host invites
 * Google to index it. This is where the site is published, which is a fact
 * about the product rather than the deployment.
 */
export const SITE_ORIGIN = "https://subrahq.com";

/** `SITE_ORIGIN` with `path` appended. `path` must start with a slash. */
export function siteUrl(path: string): string {
  return `${SITE_ORIGIN}${path}`;
}

/**
 * The share card generated by `app/opengraph-image.tsx`.
 *
 * A page that declares an `openGraph` object of its own replaces the resolved
 * one rather than merging into it, taking the file convention's image with it,
 * so any such page has to name the image again. Relative, so `metadataBase`
 * resolves it.
 */
export const OG_IMAGE = "/opengraph-image";
